name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: dotnet test
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0

        - name: dotnet test
          run: dotnet test --configuration Release

        - name: dotnet publish
          run: dotnet publish src/githubactionsdotnet.api/githubactionsdotnet.api.csproj --configuration Release -o artifacts
         
        - uses: actions/upload-artifact@v4
          with:
            name: dometrain-artifact
            path: artifacts/